/*
 * Copyright 2026 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

__var rev;

initSysPll2()
{
    __var t;

    // ANADIG_PLL_PLL_528_CTRL
    t = __readMemory32(0x40C84240, "Memory");
    if (t & 0x800000)
    {
        // SysPll2 has been initialized
        t &= ~0x40000000;
        __writeMemory32(t, 0x40C84240, "Memory");
        return;
    }

    t = __readMemory32(0x40C84270, "Memory");
    t |= 0x80808080;
    __writeMemory32(t, 0x40C84270, "Memory");

    t = __readMemory32(0x40C84240, "Memory");
    t &= ~(0x802000);
    t |= 0x40000000;
    __writeMemory32(t, 0x40C84240, "Memory");
    
    // ANADIG_PLL_PLL_528_MFN
    __writeMemory32(0, 0x40C84280, "Memory");
    // ANADIG_PLL_PLL_528_MFI
    __writeMemory32(22, 0x40C84290, "Memory");
    // ANADIG_PLL_PLL_528_MFD
    __writeMemory32(0x0FFFFFFF, 0x40C842A0, "Memory");

    // ANADIG_PLL_PLL_528_CTRL
    __writeMemory32(0x40000008, 0x40C84240, "Memory");
    __delay(30);

    // ANADIG_PLL_PLL_528_CTRL
    t = __readMemory32(0x40C84240, "Memory");
    t |= 0x800000 | 0x800;
    __writeMemory32(t, 0x40C84240, "Memory");
    __delay(250);

    t = __readMemory32(0x40C84240, "Memory");
    t &= ~0x800;
    __writeMemory32(t, 0x40C84240, "Memory");

    do
    {
        t = __readMemory32(0x40C84240, "Memory");
    } while ((t & 0x20000000) == 0);

    t |= 0x2000;
    __writeMemory32(t, 0x40C84240, "Memory");

    t &= ~0x40000000;
    __writeMemory32(t, 0x40C84240, "Memory");
}


initSysPll2Pfd1()
{
    __var t, stable;
    t = __readMemory32(0x40C84270, "Memory");
    if (((t & 0x8000) != 0) || (((t & 0x3F00) >> 8) != 16))
    {
        stable = t & 0x4000;

        t |= 0x8000;
        __writeMemory32(t, 0x40C84270, "Memory");

        t = __readMemory32(0x40C84270, "Memory");
        t &= ~0x3F00;
        t |= 16 << 8;
        __writeMemory32(t, 0x40C84270, "Memory");

        t = __readMemory32(0x40C84250, "Memory");
        t ^= 0x4;
        __writeMemory32(t, 0x40C84250, "Memory");

        t = __readMemory32(0x40C84270, "Memory");
        t &= ~0x8000;
        __writeMemory32(t, 0x40C84270, "Memory");

        do
        {
            t = __readMemory32(0x40C84270, "Memory") & 0x4000;
        } while (t == stable);
    }
    else
    {
        t &= ~0x8000;
        __writeMemory32(t, 0x40C84270, "Memory");
    }
}

_Flexspi_reset()
{
  __var reg;
   reg = __readMemory32(0x400D0000, "Memory");
  __writeMemory32((reg | 0x1), 0x400D0000, "Memory");   
  do
  {
    reg = __readMemory32(0x400D0000, "Memory");
  }while((reg & 0x1) != 0); 
}

_clock_init()
{
  __var reg;
  // Enable all clocks
  __writeMemory32(0xffffffff, 0x400FC068, "Memory");
  __writeMemory32(0xffffffff, 0x400FC06C, "Memory");
  __writeMemory32(0xffffffff, 0x400FC070, "Memory");
  __writeMemory32(0xffffffff, 0x400FC074, "Memory");
  __writeMemory32(0xffffffff, 0x400FC078, "Memory");
  __writeMemory32(0xffffffff, 0x400FC07C, "Memory");
  __writeMemory32(0xffffffff, 0x400FC080, "Memory");
  //__writeMemory32(0xffffffff, 0x400FC084, "Memory");

  // Config PLL for FlexSPI
  // PERCLK_PODF: 1 divide by 2
  __writeMemory32(0x04900001, 0x400FC01C, "Memory");
  // Enable SYS PLL but keep it bypassed.
  __writeMemory32(0x00012001, 0x400D8030, "Memory");
  do
  {
    reg = __readMemory32(0x400D8030, "Memory");
  }while((reg & 0x80000000) == 0);
  // Disable bypass of SYS PLL
  __writeMemory32(0x00002001, 0x400D8030, "Memory");
  
  // PFD2_FRAC: 29, PLL2 PFD2=528*18/PFD2_FRAC=327
  // Ungate SYS PLL PFD2
  __writeMemory32(0x001D0000, 0x400D8100, "Memory");
  
  __writeMemory32(0x44100001, 0x400FC01C, "Memory");//divide by 1
  
  __message "clock init done\n";
}

_hyper_Init()
{
  // Config IOMUX for HyperRAM
  __writeMemory32(0x00000014, 0x400E80E0, "Memory");// EMC_B2_10
  __writeMemory32(0x00000000, 0x400E858C, "Memory");
  __writeMemory32(0x00000014, 0x400E80E4, "Memory");// EMC_B2_11
  __writeMemory32(0x00000014, 0x400E80E8, "Memory");// EMC_B2_12
  __writeMemory32(0x00000014, 0x400E80EC, "Memory");// EMC_B2_13
  __writeMemory32(0x00000000, 0x400E857C, "Memory");
  __writeMemory32(0x00000014, 0x400E80F0, "Memory");// EMC_B2_14
  __writeMemory32(0x00000000, 0x400E8580, "Memory");
  __writeMemory32(0x00000014, 0x400E80F4, "Memory");// EMC_B2_15
  __writeMemory32(0x00000000, 0x400E8584, "Memory");
  __writeMemory32(0x00000014, 0x400E80F8, "Memory");// EMC_B2_16
  __writeMemory32(0x00000000, 0x400E8588, "Memory");
  __writeMemory32(0x00000014, 0x400E80FC, "Memory");// EMC_B2_17
  __writeMemory32(0x00000014, 0x400E8100, "Memory");// EMC_B2_18
  __writeMemory32(0x00000014, 0x400E8104, "Memory");// EMC_B2_19
  __writeMemory32(0x00000014, 0x400E8108, "Memory");// EMC_B2_20
  
  
  // PAD ctrl
  __writeMemory32(0x0A, 0x400E8324, "Memory");// EMC_B2_10
  __writeMemory32(0x0A, 0x400E8328, "Memory");// EMC_B2_11
  __writeMemory32(0x0A, 0x400E832C, "Memory");// EMC_B2_12
  __writeMemory32(0x0A, 0x400E8330, "Memory");// EMC_B2_13
  __writeMemory32(0x0A, 0x400E8334, "Memory");// EMC_B2_14
  __writeMemory32(0x0A, 0x400E8338, "Memory");// EMC_B2_15
  __writeMemory32(0x0A, 0x400E833C, "Memory");// EMC_B2_16
  __writeMemory32(0x0A, 0x400E8340, "Memory");// EMC_B2_17
  __writeMemory32(0x0A, 0x400E8344, "Memory");// EMC_B2_18
  __writeMemory32(0x0A, 0x400E8348, "Memory");// EMC_B2_19
  __writeMemory32(0x0A, 0x400E834C, "Memory");// EMC_B2_20

  // Config FlexSPI2 Registers

  __writeMemory32(0xFFFF80C0, 0x400D0000, "Memory"); // MCR0
  _Flexspi_reset();
  __writeMemory32(0xFFFF3032, 0x400D0000, "Memory"); // MCR0
  __writeMemory32(0xFFFFFFFF, 0x400D0004, "Memory"); // MCR1
  __writeMemory32(0x200001F7, 0x400D0008, "Memory"); // MCR2
  __writeMemory32(0x00000078, 0x400D000C, "Memory"); // AHBCR
  __writeMemory32(0x80000020, 0x400D0020, "Memory"); // AHBRXBUFCR00
  __writeMemory32(0x80000020, 0x400D0024, "Memory"); // AHBRXBUFCR01
  __writeMemory32(0x80000020, 0x400D0028, "Memory"); // AHBRXBUFCR02
  __writeMemory32(0x80000020, 0x400D002C, "Memory"); // AHBRXBUFCR03
  __writeMemory32(0x00000000, 0x400D00B8, "Memory"); // IPRXFCR
  __writeMemory32(0x00000000, 0x400D00BC, "Memory"); // IPTXFCR
  __writeMemory32(0x00002000, 0x400D0060, "Memory"); // FLASHA1CR0
  __writeMemory32(0x00021C63, 0x400D0070, "Memory"); // FLASHA1CR1
  __writeMemory32(0x00000100, 0x400D0080, "Memory"); // FLASHA1CR2
  __writeMemory32(0x00001D00, 0x400D00C0, "Memory"); // DLLCR
  __writeMemory32(0x00000000, 0x400D0094, "Memory"); // FLASHA1CR4 
  __writeMemory32(0x00000004, 0x400D0094, "Memory"); // FLASHA1CR4 
  __writeMemory32(0xFFFF3030, 0x400D0000, "Memory"); // MCR0
  __writeMemory32(0x5AF05AF0, 0x400D0018, "Memory"); // LUTKEY
  __writeMemory32(0x00000002, 0x400D001C, "Memory"); // LUTCR
  __writeMemory32(0x8B1887A0, 0x400D0200, "Memory"); // LUT[0]
  __writeMemory32(0xB7078F10, 0x400D0204, "Memory"); // LUT[1]
  __writeMemory32(0x0000A704, 0x400D0208, "Memory"); // LUT[2]
  __writeMemory32(0x00000000, 0x400D020C, "Memory"); // LUT[3] 
  __writeMemory32(0x8B188720, 0x400D0210, "Memory"); // LUT[4]
  __writeMemory32(0xB7078F10, 0x400D0214, "Memory"); // LUT[5]
  __writeMemory32(0x0000A304, 0x400D0218, "Memory"); // LUT[6]
  __writeMemory32(0x00000000, 0x400D021C, "Memory"); // LUT[7]
  __writeMemory32(0x8B1887E0, 0x400D0220, "Memory"); // LUT[8]
  __writeMemory32(0xB7078F10, 0x400D0224, "Memory"); // LUT[9]
  __writeMemory32(0x0000A704, 0x400D0228, "Memory"); // LUT[10]
  __writeMemory32(0x00000000, 0x400D022C, "Memory"); // LUT[11]
  __writeMemory32(0x8B188760, 0x400D0230, "Memory"); // LUT[12]
  __writeMemory32(0xA3048F10, 0x400D0234, "Memory"); // LUT[13]
  __writeMemory32(0x00000000, 0x400D0238, "Memory"); // LUT[14]
  __writeMemory32(0x00000000, 0x400D023C, "Memory"); // LUT[15]
  __writeMemory32(0x5AF05AF0, 0x400D0018, "Memory"); // LUTKEY
  __writeMemory32(0x00000001, 0x400D001C, "Memory"); // LUTCR
 
  _Flexspi_reset();
  
  __message "HyperRAM init done\n";
}

restoreFlexRAM()
{
    __var base;
    __var value;

    base = 0x400E4000;

    value = __readMemory32(base + 0x44, "Memory");
    value &= ~(0xFFFF);
    value |= 0xFFAA;
    __writeMemory32(value, base + 0x44, "Memory");
    value = __readMemory32(base + 0x48, "Memory");
    value &= ~(0xFFFF);
    value |= 0xFFAA;
    __writeMemory32(value, base + 0x48, "Memory");

    value = __readMemory32(base + 0x40, "Memory");
    value &= ~(0xFF << 8);
    value |= 0x7 | (0xaa << 8);
    __writeMemory32(value, base + 0x40, "Memory");
    __message "FlexRAM configuration is restored";
}

execUserPreload()
{
    restoreFlexRAM();
    _clock_init();
    _hyper_Init();
}

